name: conect and execute comand in server

on: [push]

jobs:
  build:
   runs-on: ubuntu-20.04
steps:
 uses: D3rHase/ssh-command-action@v0.2.1
  with:
     HOST: ${{secrets.HOST}}                             # Remote server address / ip - Required: true
     #PORT: ${{secrets.PORT}}                             # Remote server port -  Default: 22 - Required: false
     USER: ${{secrets.USER}}                             # Remote server user - Required: true
     PRIVATE_SSH_KEY: ${{secrets.PRIVATE_SSH_KEY}}       # Private ssh key registered on the remote server - Required: true
     COMMAND: touch entre.txt                       # Command to be executed - Default: echo Hello world! - Required: false
