name: deploy BACKend CI

#on: [push]

jobs:
  build:

   #runs-on: ubuntu-latest
        
    steps:
     - uses: actions/checkout@v3
    
     - name: ssh deploy
       uses: easingthemes/ssh-deploy@v2.2.11

       env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_SERVER_2 }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_SERVER_2 }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ./back-end/
