name: Django back-end branch CI

on:
  push:
    branches: [ "back-end" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install Django
    - name: Run Tests
      run: |
        python manage.py test
     
    - name: Install Python dependencies
      run: pip install --upgrade flake8

    - name: Run flake8
      uses: wearerequired/lint-action@v2.0.0
      with:
        flake8: true
