name: Fronted test linters
permissions:
     actions: write
on:
  # Trigger the workflow on push or pull request,
  # but only for the front branch
 push:
   branches:
     - frontend
 pull_request:
  branches:
     - frontend

jobs:
  run-linters:
    name: Run linters in frontend
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0

        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: front-end/yarn.lock
      # ESLint and Prettier must be in `package.json`
      - name: clean cache
        run: npm cache clean --force
      - name: Install Node.js dependencies
        run: |
          npm install 
          npm install prettier
      - name: Lint Action
        uses: wearerequired/lint-action@v2.0.0
        with:
           auto_fix: true
           prettier: true
           prettier_auto_fix: true
        
