# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress test Front-end

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    working-directory: /frontend
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cypress.io
      uses: cypress-io/github-action@v4.1.0
      with:
          build: npm run build
          start: npm start

    
