name: Frontttt test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - frontend

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Linting Action
        uses: ryanclark/lint-action@v1.15.0
        with:
          eslint: true
          prettier: true
