name: Frontttt test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - frontend

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0

        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: front-end/yarn.lock
      # ESLint and Prettier must be in `package.json`
      - name: clean cache
        run: npm cache clean --force
      - name: Install Node.js dependencies
        run: npm install

      - name: install xo
        run: npm install xo 
      - name: Linting Action 
        uses: ryanclark/lint-action@v1.15.0
        with:
            xo: true
