name: BACKEND TEST

on:
  push:
    branches: [ "back-end" ]

jobs:
  build:
   
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
    steps:
       - name: Checkout action
         uses: actions/checkout@v3
       - name: Django Coverage action
         uses: dc740/django-coveragepy-github-action@0.9
